#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSY1.....O"
APP_SECRET: "S9s.........="

#계좌번호 앞 8자리
CANO: "6....6"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://d.......pk8"
DISCORD_WEBHOOK_URL_MAIN: "https://d......f6F"
